// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrFgwMxCGoz6DU3ZCq-PPYHvOyOJw53Yw',
    appId: '1:893400213606:web:cbb7e9479a541dfd8fe5a7',
    messagingSenderId: '893400213606',
    projectId: 'khelkood-926c6',
    authDomain: 'khelkood-926c6.firebaseapp.com',
    storageBucket: 'khelkood-926c6.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCPnp4EKaGJJ0KArNu8fFG4jaBb6vWtWk',
    appId: '1:893400213606:ios:b32db693031ea8f68fe5a7',
    messagingSenderId: '893400213606',
    projectId: 'khelkood-926c6',
    storageBucket: 'khelkood-926c6.firebasestorage.app',
    iosBundleId: 'com.example.khelkood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrFgwMxCGoz6DU3ZCq-PPYHvOyOJw53Yw',
    appId: '1:893400213606:web:fd88a11161ef6a388fe5a7',
    messagingSenderId: '893400213606',
    projectId: 'khelkood-926c6',
    authDomain: 'khelkood-926c6.firebaseapp.com',
    storageBucket: 'khelkood-926c6.firebasestorage.app',
  );
}
